name: goreleaser

# on: [push]
on:
  pull_request:
  push:
#     tags:
#       - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    #       echo "====================================="
    #       ln -s  /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1  /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
    #       echo "====================================="
          #     echo "====================================="
          # ls /usr/lib/x86_64-linux-gnu
        

      -
        name: GCC multilib
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib clang 
          sudo apt-get install libcrypto++6 libssl1.1 libssl-dev --reinstall

      
       
         
      -
        name: OSXCross for CGO Support
        run: |
          mkdir ../../osxcross
          git clone https://github.com/likhita-809/osxcross-target.git ../../osxcross/target
          ls /home/runner/work/osxcross/target/bin

      -              
        name: find libcrypto
        run: |
          whereis libcrypto.so.1.0.0
          whereis libcrypto.so.1.1

      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.2
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}